repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: 'venv/*'
      - id: end-of-file-fixer
        exclude: 'venv/*'
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        exclude: 'venv/*'
        args: ['--ignore=E203,E501', '--max-line-length=120']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-seaborn
          - polars
          - pandas-stubs
          - matplotlib
        args: ['--exclude', '^venv/|^build/|^dist/', '--ignore-missing-imports']
